#!/usr/bin/env python

# vi: ft=python

while True:
    try:
        data = input("$ ")
    except EOFError:
        print()
        break

    if data == "bye":
        break

    if data != "":
        print(data)

print("Goodbye!")
